#ifndef CASETYPE_H_INCLUDED
#define CASETYPE_H_INCLUDED
// Différents type de case
enum CaseType{
    EMPTY, BUSH, TREE, WITH_BOMB, WITH_FIRE,
    WITH_BONUS_BOMB, WITH_BONUS_SPEED,
    WITH_BONUS_POWER, WITH_BONUS_ILL
};

#endif //CASETYPE_H_INCLUDED
