#ifndef DIRECTION_H_INCLUDED
#define DIRECTION_H_INCLUDED
// Differentes directions
enum Direction{
    DIRECTION_UP, DIRECTION_DOWN, DIRECTION_LEFT, DIRECTION_RIGHT
};

#endif //DIRECTION_H_INCLUDED

